; Exercise 1.9
; (load "sicp1.9.scm")

; Each of the following two procedures defines a method
; for adding two positive integers in terms of the procedures
; inc, which increments its argument by 1, and dec,
; which decrements its argument by 1.

; Using the substitution model, illustrate the process
; generated by each procedure in evaluating (+ 4 5).
; Are these processes iterative or recursive?

; 1 is recursive because it delays the calls to inc.
; 2 is iterative because it does not delay any calls.

(define (+ a b)
    (if (= a 0) 
      b
      (inc (+ (dec a) b))))

(+ 4 5)
(if (= 4 0)
  (false)
  (inc (+ (dec a) b)))
  (inc (+ (dec 4) 5)))
  (inc (+ (3) 5)))
  (inc (+ (3) 5)))
  (inc ((if (= 3 5)))
  (inc (((inc (+ dec 3 5)))
  (false)
  (inc (+ (dec a) b)))



(define (+ a b) (if (= a 0) b (+ (dec a) (inc b))))
(+ 4 5)
(+ 4 5) (if (= 4 0) b (+ (dec a) (inc b))))
(+ 4 5) (if (= 4 0) b (+ (dec 4) (inc 5))))
(+ 4 5) (if (= 4 0) b (+ (3) (6))))

